### ISSUE TITLE
Combine GO data with other data sources

### ISSUE THREAD

**Issue by gulfaraz** [IFRCGo/how-to-use-the-go-api#11]
A more involved example wherein we combine GO data with other APIs or static data sources.
The beneficiaries of this feature would be national societies that might just have a spreadsheet they manage with their own information about projects. In a scenario like this, we could document the process for merging that spreadsheet data with GO’s within their dashboard. E.g. a list of GO disasters filtered down dynamically based on those matching their list of projects that they have funded.

**Comment by gulfaraz** [comment]
@JonathanGarro Would it be possible to point me to APIs which we want to integrate with Go API?

**Comment by JonathanGarro** [comment]
@gulfaraz apologies for the delay. i think this is a list worth continuing to develop but off the top of my head: 

- GLIDE system https://glidenumber.net/glide/public/search/search.jsp (not sure if their API is live yet, but it was under development as of a few months ago
- ReliefWeb - https://reliefweb.int/help/api
- HDX - https://data.humdata.org/documentation
- GDACS (this might only be available as RSS, but that would still be a good scenario to explore here)
